fragment ArtworkFragment on ArtworkRecord {
	id
	title
	height
	width
	material
	location
	layout
	image {
		...ImageFragment
	}
	thumbnail: image {
		...ImageThumbnailFragment
	}
	video {
		provider
		providerUid
		thumbnailUrl
		title
		url
		width
		height
	}
	_allReferencingCollections {
		title
		year
	}
}
