query About {
	about {
		bio(markdown: false)
		email
	}
	exhibitions: allExhibitions(first: 100, orderBy: year_DESC) {
		id
		year
		title
		location
		city
		country
	}
	projects: allProjects(first: 100, orderBy: from_DESC) {
		id
		from
		until
		description
	}
	collections: allCollectionAbouts(first: 100) {
		id
		description
	}
}
