query About($first: IntType = 500, $skip: IntType = 0) {
	about {
		bio(markdown: false)
		email
	}
	allExhibitions(first: $first, skip: $skip, orderBy: year_DESC) {
		id
		year
		title
		location
		city
		country
	}
	_allExhibitionsMeta {
		count
	}
	allProjects(first: $first, skip: $skip, orderBy: from_DESC) {
		id
		from
		until
		description
	}
	_allProjectsMeta {
		count
	}
	allCollectionAbouts(first: $first, skip: $skip) {
		id
		description
	}
	_allCollectionAboutsMeta {
		count
	}
}
