query AllCollections($first: IntType = 500, $skip: IntType = 0) {
	allCollections(first: $first, skip: $skip, orderBy: year_DESC) {
		...CollectionFragment
	}
	_allCollectionsMeta {
		count
	}
}

fragment CollectionFragment on CollectionRecord {
	id
	year
	yearEnd
	title
	description
	additionalInfo
	artwork {
		...ArtworkFragment
	}
}

fragment ArtworkFragment on ArtworkRecord {
	id
	title
	height
	width
	material
	location
	layout
	multiple
	image {
		...ImageFragment
	}
	thumbnail: image {
		...ImageThumbnailFragment
	}
	video {
		provider
		providerUid
		thumbnailUrl
		title
		url
		width
		height
	}
	_allReferencingCollections(first: 100) {
		title
		year
	}
}
