query Start {
	start {
		selectedArtwork {
			...ArtworkFragment
		}
	}
	firstCollection: allCollections(first: 1, orderBy: year_ASC, filter: { year: { neq: null } }) {
		year
	}
	lastCollection: allCollections(first: 1, orderBy: year_DESC, filter: { year: { neq: null } }) {
		year
	}
}
