query Start {
	start {
		selectedArtwork {
			...ArtworkFragment
		}
	}
	firstCollection: allCollections(first: 1, orderBy: year_ASC) {
		year
	}
	lastCollection: allCollections(first: 1, orderBy: year_DESC) {
		year
	}
}
