query Start {
	start {
		loadingImage {
			...ImageFragment
		}
		backgroundImage {
			...ImageFragment
		}
	}

	firstCollection: allCollections(first: 1, orderBy: year_ASC, filter: { year: { neq: null } }) {
		year
	}
	lastCollection: allCollections(first: 1, orderBy: year_DESC, filter: { year: { neq: null } }) {
		year
	}
}
