name: backup
on:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call backup API route
        run: curl --header "Authentication:Bearer ${{GITHUB_TOKEN}}" --request GET --url 'https://www.amysimon.com/api/backup'
