name: backup
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Call backup API route
        run: curl 
          -u "${{ secrets.BASIC_AUTH_USER }}:${{ secrets.BASIC_AUTH_PASSWORD }}" 
          --request GET 
          --url "https://www.amysimon.net/api/backup"
