name: backup
on:
  schedule:
    - cron: '* * * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Call backup API route
        run: curl --username "${{secrets.BASIC_AUTH_USER}}" --password "${{secrets.BASIC_AUTH_PASSWORD}}" --request GET --url 'https://www.amysimon.net/api/backup'
